env:
  global:
    - CASADIVERSION=2.4.3
    
# works from matplotlib 1.5 onwards
#    - MPLBACKEND=Agg # Matplotlib backend; must be headless to run on travis
  

sudo: required
dist: trusty
language: generic

before_script:
  - set -e
  - set -o pipefail  # otherwise, piping with grep discards exit statuses

script:
  - cd examples
  - python tutorial_example.py

install:
  - sudo python setup.py install

before_install:
  - wget http://sourceforge.net/projects/casadi/files/CasADi/$CASADIVERSION/linux/casadi-py27-np1.9.1-v$CASADIVERSION.tar.gz/download -O casadi-py27-np1.9.1-v$CASADIVERSION.tar.gz
  - mkdir $HOME/casadi-py27-np1.9.1-v$CASADIVERSION
  - tar -zxf casadi-py27-np1.9.1-v$CASADIVERSION.tar.gz -C $HOME/casadi-py27-np1.9.1-v$CASADIVERSION
  - sudo apt-get install -y python-numpy python-scipy python-matplotlib
  - mkdir -p $HOME/.matplotlib/
  - "echo 'backend : Agg' > $HOME/.matplotlib/matplotlibrc"
  - export PYTHONPATH=$PYTHONPATH:$HOME/casadi-py27-np1.9.1-v$CASADIVERSION

